### PR TITLE
Replace std::regex with re2

### PR DESCRIPTION
**Pull request by keith**
Turns out that regexes were the bottleneck for large imports. This took
our import time from ~9s to ~4s.

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by keith** [comment]
@yongjincho92 can you share the perf win from this on your side?

**Comment by yongjincho92** [comment]
From our side the output indexstore is the same and the perf improvement is 4min 47 seconds --> 48 seconds

**Review by brentleyjones — APPROVED** [review]

**Comment by chiragramani** [comment]
Thank you for adding this change🙏🏼 🔥! I just updated our stack, and these are the numbers for our codebase:

Before remapping took(avg of 5 runs): ~72.18 seconds
Post the above changes, remapping takes(avg of 5 runs): ~16.56 seconds.

**Comment by keith** [comment]
awesome thanks for the data point! if you want to attach instruments to index-import and notice any other bottlenecks we could try to look into more fixes!

**Pull request merged**
